---
title: Bloco 'Catch' nunca alcançado; <exception> manipulado acima na mesma instrução 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62003659"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloco 'Catch' nunca alcançado; \<exceção > manipulado acima na mesma instrução 'Try'
Um `Catch` bloco no código não pode ser acessado porque ela é tratada em precedidos `Try` bloco.  
  
Por padrão, esta mensagem é um aviso. Para obter mais informações sobre como ocultar avisos ou tratar avisos como erros, consulte [Configurando avisos no Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID do erro:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Remova a instrução redundante.  
  
## <a name="see-also"></a>Consulte também

- [Como usar o bloco try/catch para capturar exceções](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Usando manipuladores de exceção filtrados por usuário](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
