---
title: Exceções
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 64a8338133c265ee1b4c7acbd9b4d168318b66a5
ms.sourcegitcommit: 5b6d778ebb269ee6684fb57ad69a8c28b06235b9
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/08/2019
ms.locfileid: "59145984"
---
# <a name="exceptions"></a><span data-ttu-id="8c556-102">Exceções</span><span class="sxs-lookup"><span data-stu-id="8c556-102">Exceptions</span></span>
<span data-ttu-id="8c556-103">Fluxos de trabalho podem usar a atividade de <xref:System.Activities.Statements.TryCatch> para manipular exceções que são geradas durante a execução de um fluxo de trabalho.</span><span class="sxs-lookup"><span data-stu-id="8c556-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="8c556-104">Essas exceções podem ser tratados ou que podem ser lançadas usando a atividade de <xref:System.Activities.Statements.Rethrow> .</span><span class="sxs-lookup"><span data-stu-id="8c556-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="8c556-105">As atividades na seção de <xref:System.Activities.Statements.TryCatch.Finally%2A> são executadas quando a seção de <xref:System.Activities.Statements.TryCatch.Try%2A> ou a seção de <xref:System.Activities.Statements.TryCatch.Catches%2A> concluírem.</span><span class="sxs-lookup"><span data-stu-id="8c556-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="8c556-106">Fluxos de trabalho hospedados por um <xref:System.Activities.WorkflowApplication> instância também pode usar o <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> manipulador de eventos para manipular exceções que não são manipuladas por um <xref:System.Activities.Statements.TryCatch> atividade.</span><span class="sxs-lookup"><span data-stu-id="8c556-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="8c556-107">Causas de exceções</span><span class="sxs-lookup"><span data-stu-id="8c556-107">Causes of Exceptions</span></span>  
 <span data-ttu-id="8c556-108">Em um fluxo de trabalho, exceções podem ser geradas das seguintes maneiras:</span><span class="sxs-lookup"><span data-stu-id="8c556-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
-   <span data-ttu-id="8c556-109">Um tempo limite de transações em <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="8c556-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
-   <span data-ttu-id="8c556-110">Uma exceção lançada explícita pelo fluxo de trabalho usando a atividade de <xref:System.Activities.Statements.Throw> .</span><span class="sxs-lookup"><span data-stu-id="8c556-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
-   <span data-ttu-id="8c556-111">Uma exceção lançada de [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] de uma atividade.</span><span class="sxs-lookup"><span data-stu-id="8c556-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
-   <span data-ttu-id="8c556-112">Uma exceção acionada de código externo, como bibliotecas, componentes, ou serviços que são usados no fluxo de trabalho.</span><span class="sxs-lookup"><span data-stu-id="8c556-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="8c556-113">Tratando exceções</span><span class="sxs-lookup"><span data-stu-id="8c556-113">Handling Exceptions</span></span>  
 <span data-ttu-id="8c556-114">Se uma exceção é acionada por uma atividade e é não tratada, o comportamento padrão é finalizar a instância de fluxo de trabalho.</span><span class="sxs-lookup"><span data-stu-id="8c556-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="8c556-115">Se um manipulador de <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> personalizado estiver presente, pode substituir esse comportamento padrão.</span><span class="sxs-lookup"><span data-stu-id="8c556-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="8c556-116">Esse manipulador fornece o autor do host de fluxo de trabalho uma oportunidade para fornecer tratamento apropriado, como o log personalizado, anulando o fluxo de trabalho, cancelar o fluxo de trabalho, ou de terminação o fluxo de trabalho.</span><span class="sxs-lookup"><span data-stu-id="8c556-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="8c556-117">Se um fluxo de trabalho gerencie uma exceção que não é tratada, o manipulador de <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> é chamado.</span><span class="sxs-lookup"><span data-stu-id="8c556-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="8c556-118">Há três ações possíveis retornadas de <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> que determinam o resultado final de fluxo de trabalho.</span><span class="sxs-lookup"><span data-stu-id="8c556-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
-   <span data-ttu-id="8c556-119">**Cancelar** -uma instância de fluxo de trabalho cancelado é uma saída normal de uma execução de ramificação.</span><span class="sxs-lookup"><span data-stu-id="8c556-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="8c556-120">Você pode modelar o comportamento de cancelamento (por exemplo, usando uma atividade de CancellationScope).</span><span class="sxs-lookup"><span data-stu-id="8c556-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="8c556-121">O manipulador concluído é chamado quando o processo de cancelamento completa.</span><span class="sxs-lookup"><span data-stu-id="8c556-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="8c556-122">Um fluxo de trabalho cancelado está no estado cancelado.</span><span class="sxs-lookup"><span data-stu-id="8c556-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
-   <span data-ttu-id="8c556-123">**Encerrar** -uma instância de fluxo de trabalho encerrado não pode ser continuada ou reiniciada.</span><span class="sxs-lookup"><span data-stu-id="8c556-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="8c556-124">Isso dispara o evento concluído em que você pode fornecer uma exceção que a razão ele foi finalizada.</span><span class="sxs-lookup"><span data-stu-id="8c556-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="8c556-125">O manipulador encerrado é chamado quando o processo de fim completa.</span><span class="sxs-lookup"><span data-stu-id="8c556-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="8c556-126">Um fluxo de trabalho encerrado está no estado criticado.</span><span class="sxs-lookup"><span data-stu-id="8c556-126">A terminated workflow is in the Faulted state.</span></span>  
  
-   <span data-ttu-id="8c556-127">**Anular** -uma instância de fluxo de trabalho anuladas pode ser retomado somente se ele foi configurado para ser persistente.</span><span class="sxs-lookup"><span data-stu-id="8c556-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="8c556-128">Sem persistência, um fluxo de trabalho não pode ser continuado.</span><span class="sxs-lookup"><span data-stu-id="8c556-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="8c556-129">No ponto um fluxo de trabalho é anuladas, alguns funciona feito (na memória) como o ponto que o último de persistência será perdido.</span><span class="sxs-lookup"><span data-stu-id="8c556-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="8c556-130">Para um fluxo de trabalho anuladas, o manipulador anuladas é chamado usando a exceção como a razão quando o processo de abort completa.</span><span class="sxs-lookup"><span data-stu-id="8c556-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="8c556-131">No entanto, diferentemente de cancelado e de finalizado, o manipulador concluído não é chamado.</span><span class="sxs-lookup"><span data-stu-id="8c556-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="8c556-132">Um fluxo de trabalho anuladas está em um estado anuladas.</span><span class="sxs-lookup"><span data-stu-id="8c556-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="8c556-133">O exemplo a seguir chama um fluxo de trabalho que gerencia uma exceção.</span><span class="sxs-lookup"><span data-stu-id="8c556-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="8c556-134">A exceção é não tratados pelo fluxo de trabalho e o manipulador de <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> é chamado.</span><span class="sxs-lookup"><span data-stu-id="8c556-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="8c556-135"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> é inspecionado para fornecer informações sobre a exceção, e fluxo de trabalho é encerrado.</span><span class="sxs-lookup"><span data-stu-id="8c556-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="8c556-136">Manipulando exceções com a atividade de TryCatch</span><span class="sxs-lookup"><span data-stu-id="8c556-136">Handling Exceptions with the TryCatch Activity</span></span>  
 <span data-ttu-id="8c556-137">Manipulando exceções dentro de um fluxo de trabalho é executado pela atividade de <xref:System.Activities.Statements.TryCatch> .</span><span class="sxs-lookup"><span data-stu-id="8c556-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="8c556-138">A atividade de <xref:System.Activities.Statements.TryCatch> tem uma coleção de <xref:System.Activities.Statements.TryCatch.Catches%2A> de atividades de <xref:System.Activities.Statements.Catch> que são associadas com um tipo específico de <xref:System.Exception> .</span><span class="sxs-lookup"><span data-stu-id="8c556-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="8c556-139">Se a exceção acionada por uma atividade que está contida na seção de <xref:System.Activities.Statements.TryCatch.Try%2A> de uma atividade de <xref:System.Activities.Statements.TryCatch> corresponde a exceção de uma atividade de <xref:System.Activities.Statements.Catch%601> na coleção de <xref:System.Activities.Statements.TryCatch.Catches%2A> , então a exceção é tratada.</span><span class="sxs-lookup"><span data-stu-id="8c556-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="8c556-140">Se a exceção é lançada novamente ou explicitamente uma nova exceção é lançada então passa essa exceção até a atividade pai.</span><span class="sxs-lookup"><span data-stu-id="8c556-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="8c556-141">O exemplo de código a seguir mostra uma atividade de <xref:System.Activities.Statements.TryCatch> que manipula <xref:System.ApplicationException> que é gerada na seção de <xref:System.Activities.Statements.TryCatch.Try%2A> por uma atividade de <xref:System.Activities.Statements.Throw> .</span><span class="sxs-lookup"><span data-stu-id="8c556-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="8c556-142">A mensagem de exceção é escrita para o console pela atividade de <xref:System.Activities.Statements.Catch%601> , e uma mensagem é gravada no console na seção de <xref:System.Activities.Statements.TryCatch.Finally%2A> .</span><span class="sxs-lookup"><span data-stu-id="8c556-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="8c556-143">As atividades na seção de <xref:System.Activities.Statements.TryCatch.Finally%2A> são executadas quando a seção de <xref:System.Activities.Statements.TryCatch.Try%2A> ou a seção de <xref:System.Activities.Statements.TryCatch.Catches%2A> completa com êxito.</span><span class="sxs-lookup"><span data-stu-id="8c556-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="8c556-144">A seção de <xref:System.Activities.Statements.TryCatch.Try%2A> concluída com êxito se nenhuma exceção é lançada deles, e a seção de <xref:System.Activities.Statements.TryCatch.Catches%2A> concluída com êxito se nenhuma exceção é lançada ou rethrown deles.</span><span class="sxs-lookup"><span data-stu-id="8c556-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="8c556-145">Se uma exceção é lançada na seção de <xref:System.Activities.Statements.TryCatch.Try%2A> de <xref:System.Activities.Statements.TryCatch> e não é tratada por <xref:System.Activities.Statements.Catch%601> na seção de <xref:System.Activities.Statements.TryCatch.Catches%2A> , nem é rethrown de <xref:System.Activities.Statements.TryCatch.Catches%2A>, as atividades em <xref:System.Activities.Statements.TryCatch.Finally%2A> não serão executadas a menos que o da seguir ocorrer.</span><span class="sxs-lookup"><span data-stu-id="8c556-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
-   <span data-ttu-id="8c556-146">A exceção é detectada por uma atividade de alto nível de <xref:System.Activities.Statements.TryCatch> no fluxo de trabalho, independentemente se é rethrown do <xref:System.Activities.Statements.TryCatch>de alto nível.</span><span class="sxs-lookup"><span data-stu-id="8c556-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
-   <span data-ttu-id="8c556-147">A exceção não é tratada por <xref:System.Activities.Statements.TryCatch>de alto nível, libera a raiz de trabalho, e o trabalho são configurados para cancelar em vez de finalizam ou exibe.</span><span class="sxs-lookup"><span data-stu-id="8c556-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="8c556-148">Fluxos de trabalho usando <xref:System.Activities.WorkflowApplication> hospedados podem configurar esse manipulando <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> e retornando <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="8c556-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="8c556-149">Um exemplo de manipular <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> é fornecido anteriormente neste tópico.</span><span class="sxs-lookup"><span data-stu-id="8c556-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="8c556-150">Os serviços de fluxo de trabalho podem configurar isso usando <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> e especificando <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="8c556-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="8c556-151">Para obter um exemplo de configuração <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, consulte [extensibilidade de Host de serviço de fluxo de trabalho](../wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="8c556-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="8c556-152">Manipulação de exceção com a compensação</span><span class="sxs-lookup"><span data-stu-id="8c556-152">Exception Handling versus Compensation</span></span>  
 <span data-ttu-id="8c556-153">A diferença entre a manipulação de exceção e a compensação é que a manipulação de exceção ocorre durante a execução de uma atividade.</span><span class="sxs-lookup"><span data-stu-id="8c556-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="8c556-154">A compensação ocorre após uma atividade terminou com êxito.</span><span class="sxs-lookup"><span data-stu-id="8c556-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="8c556-155">Manipulação de exceção fornece uma oportunidade para limpar após a atividade gerencie a exceção, enquanto a compensação fornece um mecanismo por que o trabalho com êxito concluído de uma atividade anteriormente pode ser concluída desfeito.</span><span class="sxs-lookup"><span data-stu-id="8c556-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="8c556-156">Para obter mais informações, consulte [compensação](compensation.md).</span><span class="sxs-lookup"><span data-stu-id="8c556-156">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="8c556-157">Consulte também</span><span class="sxs-lookup"><span data-stu-id="8c556-157">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
