---
title: Como tratar uma exceção usando o guia de programação do try-catch-C#
description: Saiba como tratar uma exceção usando um bloco try-catch. Consulte um exemplo de código e exiba recursos adicionais disponíveis.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 357aebe042bc5b6e761b3c1bad258021441de22c
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 07/28/2020
ms.locfileid: "87301990"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="f4c96-104">Como tratar uma exceção usando try/catch (guia de programação C#)</span><span class="sxs-lookup"><span data-stu-id="f4c96-104">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="f4c96-105">A finalidade de um bloco [try-catch](../../language-reference/keywords/try-catch.md) é capturar e manipular uma exceção gerada pelo código de trabalho.</span><span class="sxs-lookup"><span data-stu-id="f4c96-105">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="f4c96-106">Algumas exceções podem ser manipuladas em um bloco `catch` e o problema pode ser resolvido sem que a exceção seja gerada novamente. No entanto, com mais frequência, a única coisa que você pode fazer é certificar-se de que a exceção apropriada seja gerada.</span><span class="sxs-lookup"><span data-stu-id="f4c96-106">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="f4c96-107">Exemplo</span><span class="sxs-lookup"><span data-stu-id="f4c96-107">Example</span></span>  
 <span data-ttu-id="f4c96-108">Neste exemplo, <xref:System.IndexOutOfRangeException> não é a exceção mais apropriada: <xref:System.ArgumentOutOfRangeException> faz mais sentido para o método porque o erro é causado pelo argumento `index` passado pelo chamador.</span><span class="sxs-lookup"><span data-stu-id="f4c96-108">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="f4c96-109">Comentários</span><span class="sxs-lookup"><span data-stu-id="f4c96-109">Comments</span></span>  
 <span data-ttu-id="f4c96-110">O código que causa uma exceção fica dentro do bloco `try`.</span><span class="sxs-lookup"><span data-stu-id="f4c96-110">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="f4c96-111">A instrução `catch` é adicionada logo após para manipular `IndexOutOfRangeException`, se ocorrer.</span><span class="sxs-lookup"><span data-stu-id="f4c96-111">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="f4c96-112">O bloco `catch` manipula o `IndexOutOfRangeException` e gera a exceção `ArgumentOutOfRangeException`, que é mais adequada.</span><span class="sxs-lookup"><span data-stu-id="f4c96-112">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="f4c96-113">Para fornecer ao chamador tantas informações quanto possível, considere especificar a exceção original como o <xref:System.Exception.InnerException%2A> da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="f4c96-113">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="f4c96-114">Como a <xref:System.Exception.InnerException%2A> propriedade é [somente leitura](../../properties.md#read-only), você deve atribuí-la no construtor da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="f4c96-114">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="f4c96-115">Veja também</span><span class="sxs-lookup"><span data-stu-id="f4c96-115">See also</span></span>

- [<span data-ttu-id="f4c96-116">Guia de programação C#</span><span class="sxs-lookup"><span data-stu-id="f4c96-116">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="f4c96-117">Exceções e tratamento de exceções</span><span class="sxs-lookup"><span data-stu-id="f4c96-117">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="f4c96-118">Tratamento de exceção</span><span class="sxs-lookup"><span data-stu-id="f4c96-118">Exception Handling</span></span>](./exception-handling.md)
