---
title: Como manipular uma exceção usando try-catch (Guia de programação em C#)
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: b67a3d7b6d2e10519363a273b7dd1d8b61317d1c
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 05/04/2018
ms.locfileid: "33338065"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="991c6-102">Como manipular uma exceção usando try/catch (Guia de Programação em C#)</span><span class="sxs-lookup"><span data-stu-id="991c6-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="991c6-103">A finalidade de um bloco [try-catch](../../../csharp/language-reference/keywords/try-catch.md) é capturar e manipular uma exceção gerada pelo código de trabalho.</span><span class="sxs-lookup"><span data-stu-id="991c6-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="991c6-104">Algumas exceções podem ser manipuladas em um bloco `catch` e o problema pode ser resolvido sem que a exceção seja gerada novamente. No entanto, com mais frequência, a única coisa que você pode fazer é certificar-se de que a exceção apropriada seja gerada.</span><span class="sxs-lookup"><span data-stu-id="991c6-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="991c6-105">Exemplo</span><span class="sxs-lookup"><span data-stu-id="991c6-105">Example</span></span>  
 <span data-ttu-id="991c6-106">Neste exemplo, <xref:System.IndexOutOfRangeException> não é a exceção mais apropriada: <xref:System.ArgumentOutOfRangeException> faz mais sentido para o método porque o erro é causado pelo argumento `index` passado pelo chamador.</span><span class="sxs-lookup"><span data-stu-id="991c6-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]  
  
## <a name="comments"></a><span data-ttu-id="991c6-107">Comentários</span><span class="sxs-lookup"><span data-stu-id="991c6-107">Comments</span></span>  
 <span data-ttu-id="991c6-108">O código que causa uma exceção fica dentro do bloco `try`.</span><span class="sxs-lookup"><span data-stu-id="991c6-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="991c6-109">A instrução `catch` é adicionada logo após para manipular `IndexOutOfRangeException`, se ocorrer.</span><span class="sxs-lookup"><span data-stu-id="991c6-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="991c6-110">O bloco `catch` manipula o `IndexOutOfRangeException` e gera a exceção `ArgumentOutOfRangeException`, que é mais adequada.</span><span class="sxs-lookup"><span data-stu-id="991c6-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="991c6-111">Para fornecer ao chamador tantas informações quanto possível, considere especificar a exceção original como o <xref:System.Exception.InnerException%2A> da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="991c6-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="991c6-112">Uma vez que a propriedade <xref:System.Exception.InnerException%2A> é [readonly](../../../csharp/language-reference/keywords/readonly.md), você precisa atribuí-la no construtor da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="991c6-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="991c6-113">Consulte também</span><span class="sxs-lookup"><span data-stu-id="991c6-113">See Also</span></span>  
 [<span data-ttu-id="991c6-114">Guia de Programação em C#</span><span class="sxs-lookup"><span data-stu-id="991c6-114">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)  
 [<span data-ttu-id="991c6-115">Exceções e manipulação de exceções</span><span class="sxs-lookup"><span data-stu-id="991c6-115">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)  
 [<span data-ttu-id="991c6-116">Tratamento de Exceção</span><span class="sxs-lookup"><span data-stu-id="991c6-116">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)
